using System;
using System.IO;
using System.Linq;
using System.Diagnostics;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Media3D;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Microsoft.Win32;
using Forms=System.Windows.Forms;

namespace DC3 {
public class Entry {
    public string Path,Display; public string FullPath {get{return Path;}} public override string ToString(){return Display;}
}
public class Viewer : Window {
    public Model Current; public Viewport3D View=new Viewport3D();
    PerspectiveCamera Camera=new PerspectiveCamera(); Model3DGroup Stage=new Model3DGroup(),Lines=new Model3DGroup(),Floor=new Model3DGroup();
    TextBlock Status,TitleText,Stats,TimeText,ResultText;TextBox Search;ListBox Library;ComboBox ClipBox,TextureBox,SpeedBox,TypeBox;StackPanel MeshList;Slider Timeline;Button Play,BackFrame,NextFrame;
    CheckBox Bones,Wire,Grid,Loop;List<Entry> Entries=new List<Entry>();DispatcherTimer Timer=new DispatcherTimer();Stopwatch Watch=new Stopwatch();
    bool Playing,Updating,Loading;int ClipIndex=-1,LoadGeneration;double Time,FloorHeight,Distance=5,Yaw=.8,Pitch=.3,Radius=1;Point3D Center;Point Last;MouseButton DragButton;
    string GlbPath,LibraryRoot; bool Exporting; int LibraryGeneration;Brush Fore=new SolidColorBrush(Color.FromRgb(220,232,228)),PanelBrush=new LinearGradientBrush(Color.FromRgb(19,38,41),Color.FromRgb(5,16,20),90),Accent=new SolidColorBrush(Color.FromRgb(176,209,200));
    public Viewer(){
        Title="Dino Crisis 3 Model Viewer 0.8.5";Width=1280;Height=820;MinWidth=920;MinHeight=600;Background=new SolidColorBrush(Color.FromRgb(5,14,17));Foreground=Fore;FontFamily=new FontFamily("Segoe UI");FontSize=13;
        using(var theme=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("DC3.Theme.xaml"))Resources.MergedDictionaries.Add((ResourceDictionary)System.Windows.Markup.XamlReader.Load(theme));
        using(var iconStream=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("DC3.AppIcon.ico")){var decoder=new IconBitmapDecoder(iconStream,BitmapCreateOptions.PreservePixelFormat,BitmapCacheOption.OnLoad);Icon=decoder.Frames.OrderByDescending(frame=>frame.PixelWidth).First();}
        var outer=new DockPanel{Background=Background};Content=outer;
        var top=new StackPanel{Orientation=Orientation.Horizontal,Background=PanelBrush,Height=90};DockPanel.SetDock(top,Dock.Top);outer.Children.Add(top);
        var logo=new BitmapImage();using(var stream=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("DC3.Logo.png")){logo.BeginInit();logo.CacheOption=BitmapCacheOption.OnLoad;logo.StreamSource=stream;logo.EndInit();logo.Freeze();}var brand=new Image{Source=logo,Width=190,Height=63,Stretch=Stretch.Uniform,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(20,0,14,0),ToolTip="Dino Crisis 3"};RenderOptions.SetBitmapScalingMode(brand,BitmapScalingMode.HighQuality);System.Windows.Automation.AutomationProperties.SetName(brand,"Dino Crisis 3");var brandPanel=new StackPanel{VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(20,0,24,0)};brand.Margin=new Thickness(0);brandPanel.Children.Add(brand);
        var subtitle=new BitmapImage();using(var stream=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("DC3.Subtitle.png")){subtitle.BeginInit();subtitle.CacheOption=BitmapCacheOption.OnLoad;subtitle.StreamSource=stream;subtitle.EndInit();subtitle.Freeze();}var subtitleCrop=new CroppedBitmap(subtitle,new Int32Rect(0,(int)(subtitle.PixelHeight*.28),subtitle.PixelWidth,(int)(subtitle.PixelHeight*.43)));subtitleCrop.Freeze();var subtitleImage=new Image{Source=subtitleCrop,Width=174,Height=24,Stretch=Stretch.Uniform,HorizontalAlignment=HorizontalAlignment.Center};RenderOptions.SetBitmapScalingMode(subtitleImage,BitmapScalingMode.HighQuality);System.Windows.Automation.AutomationProperties.SetName(subtitleImage,"Model Viewer");brandPanel.Children.Add(subtitleImage);top.Children.Add(brandPanel);
        top.Children.Add(Button("Open ITK…",async delegate{var dialog=new OpenFileDialog{Filter="Dino Crisis archives (*.itk)|*.itk"};if(dialog.ShowDialog()==true)await Open(dialog.FileName);}));
        top.Children.Add(Button("Open model…",async delegate{var dialog=new OpenFileDialog{Filter="Dino Crisis models (*.xom;*.glb)|*.xom;*.glb"};if(dialog.ShowDialog()==true)await Open(dialog.FileName);}));
        top.Children.Add(Button("Open folder…",async delegate{using(var dialog=new Forms.FolderBrowserDialog()){dialog.Description="Choose extracted Dino Crisis 3 models";if(dialog.ShowDialog()==Forms.DialogResult.OK)await Scan(dialog.SelectedPath);}}));
        top.Children.Add(Button("Export assets…",async delegate{await ExportAssets();}));
        top.Children.Add(Button("Save GLB…",delegate{Export();}));top.Children.Add(Button("Frame model",delegate{Frame();}));foreach(var button in top.Children.OfType<Button>())button.VerticalAlignment=VerticalAlignment.Center;
        var footer=new DockPanel{Background=PanelBrush,Height=65};DockPanel.SetDock(footer,Dock.Bottom);outer.Children.Add(footer);
        Play=Button("Play",delegate{TogglePlayback();});Play.IsEnabled=false;DockPanel.SetDock(Play,Dock.Left);footer.Children.Add(Play);
        var back=BackFrame=Button("−1 frame",delegate{Seek(Time-1.0/30);});DockPanel.SetDock(back,Dock.Left);footer.Children.Add(back);
        var next=NextFrame=Button("+1 frame",delegate{Seek(Time+1.0/30);});DockPanel.SetDock(next,Dock.Right);footer.Children.Add(next);
        TimeText=new TextBlock{Text="0.00 / 0.00 s",Width=130,VerticalAlignment=VerticalAlignment.Center,TextAlignment=TextAlignment.Center};DockPanel.SetDock(TimeText,Dock.Right);footer.Children.Add(TimeText);
        Timeline=new Slider{Minimum=0,Maximum=1,Margin=new Thickness(15,0,15,0),VerticalAlignment=VerticalAlignment.Center,IsMoveToPointEnabled=true};Timeline.ValueChanged+=delegate{if(!Updating)Seek(Timeline.Value);};footer.Children.Add(Timeline);
        var body=new System.Windows.Controls.Grid();body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(250)});body.ColumnDefinitions.Add(new ColumnDefinition());body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(240)});outer.Children.Add(body);
        var left=new DockPanel{Background=PanelBrush,Margin=new Thickness(0,1,1,0)};System.Windows.Controls.Grid.SetColumn(left,0);body.Children.Add(left);
        var libraryHead=new StackPanel{Margin=new Thickness(16)};DockPanel.SetDock(libraryHead,Dock.Top);left.Children.Add(libraryHead);libraryHead.Children.Add(Label("ASSET LIBRARY",true));Search=new TextBox{Margin=new Thickness(0,12,0,6),Padding=new Thickness(8),Background=Background,Foreground=Fore};Search.TextChanged+=delegate{Filter();};libraryHead.Children.Add(Search);libraryHead.Children.Add(Label("Search: en013, .xom or *.xom"));
        TypeBox=Combo(libraryHead,"File type");foreach(string type in new[]{"All files","Models","Animations","Textures","Audio / music","Video","Archives","Other"})TypeBox.Items.Add(type);TypeBox.SelectedIndex=0;TypeBox.SelectionChanged+=delegate{Filter();};
        libraryHead.Children.Add(Button("Clear filters",delegate{Search.Text="";TypeBox.SelectedIndex=0;Filter();}));
        ResultText=Label("Open an ITK or folder to browse files.");libraryHead.Children.Add(ResultText);
        libraryHead.Children.Add(Button("Save selected file…",delegate{SaveSelected();}));
        Library=new ListBox{Background=PanelBrush,Foreground=Fore,BorderThickness=new Thickness(0),Margin=new Thickness(8)};var itemStyle=new Style(typeof(ListBoxItem),(Style)FindResource(typeof(ListBoxItem)));itemStyle.Setters.Add(new Setter(ToolTipService.ToolTipProperty,new System.Windows.Data.Binding("FullPath")));Library.ItemContainerStyle=itemStyle;Library.SelectionChanged+=async delegate{var e=Library.SelectedItem as Entry;if(e!=null)await SelectAsset(e.Path);};left.Children.Add(Library);
        var middle=new System.Windows.Controls.Grid();middle.ClipToBounds=true;System.Windows.Controls.Grid.SetColumn(middle,1);body.Children.Add(middle);View.Camera=Camera;View.ClipToBounds=true;middle.Children.Add(View);
        Camera.FieldOfView=40;Camera.UpDirection=new Vector3D(0,1,0);Camera.NearPlaneDistance=.001;Camera.FarPlaneDistance=10000;
        var lights=new Model3DGroup();lights.Children.Add(new AmbientLight(Color.FromRgb(115,115,125)));lights.Children.Add(new DirectionalLight(Color.FromRgb(230,220,209),new Vector3D(-1,-2,-1)));lights.Children.Add(new DirectionalLight(Color.FromRgb(100,145,180),new Vector3D(1,-.5,1)));Stage.Children.Add(lights);Stage.Children.Add(Floor);Stage.Children.Add(Lines);View.Children.Add(new ModelVisual3D{Content=Stage});
        var hud=new StackPanel{Margin=new Thickness(24),VerticalAlignment=VerticalAlignment.Top,IsHitTestVisible=false};middle.Children.Add(hud);hud.Children.Add(Label("MODEL INSPECTION",true));TitleText=new TextBlock{Text="Choose a model",FontSize=28,FontFamily=new FontFamily("Bahnschrift"),Margin=new Thickness(0,10,0,8)};Stats=Label("Open ITK to browse models, or open an XOM / GLB.");Status=Label("Ready");Status.Foreground=Accent;Status.TextWrapping=TextWrapping.Wrap;Status.Margin=new Thickness(0,16,0,0);hud.Children.Add(TitleText);hud.Children.Add(Stats);hud.Children.Add(Status);
        var hints=Label("Drag to orbit · Right-drag to pan · Scroll to zoom · Space to play");hints.HorizontalAlignment=HorizontalAlignment.Center;hints.VerticalAlignment=VerticalAlignment.Bottom;hints.Margin=new Thickness(8,0,8,15);hints.IsHitTestVisible=false;middle.Children.Add(hints);
        middle.Background=Brushes.Transparent;middle.MouseDown+=delegate(object s,MouseButtonEventArgs e){Last=e.GetPosition(middle);DragButton=e.ChangedButton;middle.CaptureMouse();};middle.MouseUp+=delegate{middle.ReleaseMouseCapture();};middle.MouseMove+=delegate(object s,MouseEventArgs e){if(!middle.IsMouseCaptured)return;Point p=e.GetPosition(middle);double dx=p.X-Last.X,dy=p.Y-Last.Y;Last=p;if(DragButton==MouseButton.Left){Yaw-=dx*.008;Pitch=Math.Max(-1.45,Math.Min(1.45,Pitch+dy*.008));}else{var right=new Vector3D(Math.Cos(Yaw),0,-Math.Sin(Yaw));Center+=right*(-dx*Distance*.0015)+new Vector3D(0,dy*Distance*.0015,0);}CameraUpdate();};middle.MouseWheel+=delegate(object s,MouseWheelEventArgs e){Distance=Math.Max(Radius*.05,Math.Min(Radius*150,Distance*Math.Pow(.88,e.Delta/120.0)));CameraUpdate();};
        var inspector=new StackPanel{Margin=new Thickness(18)};var scroll=new ScrollViewer{Content=inspector,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Background=PanelBrush};System.Windows.Controls.Grid.SetColumn(scroll,2);body.Children.Add(scroll);
        inspector.Children.Add(Label("ANIMATION",true));ClipBox=Combo(inspector,"Clip");ClipBox.Items.Add("Rest pose");ClipBox.SelectedIndex=0;ClipBox.SelectionChanged+=delegate{if(Loading)return;ClipIndex=ClipBox.SelectedIndex-1;Playing=false;Play.Content="Play";Play.IsEnabled=ClipIndex>=0;Time=0;Pose();AlignFloor();};
        SpeedBox=Combo(inspector,"Playback speed");foreach(var speed in new[]{"0.25×","0.5×","1×","2×"})SpeedBox.Items.Add(speed);SpeedBox.SelectedIndex=2;Loop=Check(inspector,"Loop clip",delegate{});Loop.IsChecked=false;
        inspector.Children.Add(new Border{Height=22});inspector.Children.Add(Label("DISPLAY",true));Wire=Check(inspector,"Wireframe",delegate{Pose();});Bones=Check(inspector,"Skeleton",delegate{Overlays();});Grid=Check(inspector,"Ground grid",delegate{DrawGrid();});Grid.IsChecked=true;inspector.Children.Add(Button("Align floor to pose",delegate{AlignFloor();}));
        TextureBox=Combo(inspector,"Override all mesh textures");TextureBox.Items.Add("Per-mesh materials");TextureBox.SelectedIndex=0;TextureBox.SelectionChanged+=delegate{if(Current==null||Loading)return;foreach(var p in Current.Parts){var mat=TextureBox.SelectedIndex>0?Model.Textured(Current.Textures[TextureBox.SelectedIndex-1]):p.OriginalMaterial;p.Visual.Material=mat;p.Visual.BackMaterial=mat;}Pose();};
        var note=Label("Base textures load per mesh when supported. Use the selectors below for individual overrides.");note.TextWrapping=TextWrapping.Wrap;note.Margin=new Thickness(0,12,0,20);inspector.Children.Add(note);inspector.Children.Add(Label("MESHES",true));MeshList=new StackPanel();inspector.Children.Add(MeshList);
        Timer.Interval=TimeSpan.FromSeconds(1.0/30);Timer.Tick+=delegate{double dt=Watch.Elapsed.TotalSeconds;Watch.Restart();TickPlayback(dt);};Timer.Start();Watch.Start();
        KeyDown+=delegate(object s,KeyEventArgs e){if(e.Key==Key.Space&&!(Keyboard.FocusedElement is TextBox)&&!(Keyboard.FocusedElement is ComboBox)){TogglePlayback();e.Handled=true;}};
        AllowDrop=true;Drop+=async delegate(object s,DragEventArgs e){if(e.Data.GetDataPresent(DataFormats.FileDrop)){var files=(string[])e.Data.GetData(DataFormats.FileDrop);if(files.Length>0)await Open(files[0]);}};
        Closed+=delegate{Timer.Stop();};SyncPlaybackControls();CameraUpdate();
    }
    TextBlock Label(string text,bool heading=false){return new TextBlock{Text=text,Foreground=heading?Accent:new SolidColorBrush(Color.FromRgb(152,177,177)),FontSize=heading?12:12,FontFamily=new FontFamily(heading?"Bahnschrift":"Segoe UI"),FontWeight=heading?FontWeights.SemiBold:FontWeights.Normal,TextWrapping=TextWrapping.Wrap};}
    Button Button(string text,RoutedEventHandler action){var b=new Button{Content=text,FontFamily=new FontFamily("Bahnschrift"),Padding=new Thickness(13,8,13,8),Margin=new Thickness(6,12,6,12),Background=new SolidColorBrush(Color.FromRgb(43,61,76)),Foreground=Fore,BorderBrush=new SolidColorBrush(Color.FromRgb(70,88,103))};b.Click+=action;return b;}
    ComboBox Combo(StackPanel panel,string label){var t=Label(label);t.Margin=new Thickness(0,18,0,6);panel.Children.Add(t);var c=new ComboBox{Foreground=Fore,Padding=new Thickness(6),MaxDropDownHeight=320};panel.Children.Add(c);return c;}
    CheckBox Check(StackPanel panel,string text,RoutedEventHandler change){var c=new CheckBox{Content=text,Foreground=Fore,Margin=new Thickness(0,10,0,3)};c.Checked+=change;c.Unchecked+=change;panel.Children.Add(c);return c;}
    public async Task Scan(string directory){int generation=++LibraryGeneration;try{Status.Text="Scanning files…";var entries=await Task.Run(()=>BrowseFiles(directory));if(generation!=LibraryGeneration)return;LibraryRoot=directory;Entries=entries;Filter();Status.Text=Entries.Count+" files found. Select a model to preview.";}catch(Exception e){if(generation==LibraryGeneration)Status.Text="Could not scan folder: "+e.Message;}}
    public static List<Entry> BrowseFiles(string directory){return Directory.EnumerateFiles(directory,"*",SearchOption.AllDirectories).Where(x=>!Path.GetFileName(x).Equals("manifest.json",StringComparison.OrdinalIgnoreCase)).Select(x=>new Entry{Path=x,Display=Path.GetFileName(x)+"  /  "+MakeRelative(directory,x)}).OrderBy(x=>x.Display).ToList();}
    static string MakeRelative(string root,string path){return path.Substring(root.TrimEnd(Path.DirectorySeparatorChar).Length).TrimStart(Path.DirectorySeparatorChar);}
    static string Category(string path){switch(Path.GetExtension(path).ToLowerInvariant()){case ".xom":case ".glb":return "Models";case ".xoa":return "Animations";case ".xtx":case ".png":case ".dds":case ".bmp":case ".jpg":return "Textures";case ".xss":case ".xsp":case ".wav":case ".ogg":case ".mp3":case ".aif":case ".aiff":case ".wma":return "Audio / music";case ".bik":case ".xmv":case ".wmv":case ".avi":case ".mp4":case ".sfd":return "Video";case ".itk":return "Archives";default:return "Other";}}
    static bool SearchMatches(Entry entry,string query){query=(query??"").Trim();if(query.Length==0)return true;if(query.IndexOfAny(new[]{'*','?'})<0)return entry.Display.IndexOf(query,StringComparison.OrdinalIgnoreCase)>=0;
        string pattern=System.Text.RegularExpressions.Regex.Escape(query).Replace("\\*",".*").Replace("\\?",".");
        return System.Text.RegularExpressions.Regex.IsMatch(Path.GetFileName(entry.Path),"^"+pattern+"$",System.Text.RegularExpressions.RegexOptions.IgnoreCase|System.Text.RegularExpressions.RegexOptions.CultureInvariant,TimeSpan.FromMilliseconds(100))||System.Text.RegularExpressions.Regex.IsMatch(entry.Path,"^.*[\\\\/]"+pattern+"$",System.Text.RegularExpressions.RegexOptions.IgnoreCase|System.Text.RegularExpressions.RegexOptions.CultureInvariant,TimeSpan.FromMilliseconds(100));}
    void Filter(){if(Library==null)return;string kind=TypeBox==null?"All files":TypeBox.SelectedItem as string;var matches=Entries.Where(x=>SearchMatches(x,Search.Text)&&(kind=="All files"||kind==null||Category(x.Path)==kind)).ToList();Library.ItemsSource=matches;if(ResultText!=null){int models=Entries.Count(x=>Path.GetExtension(x.Path).Equals(".xom",StringComparison.OrdinalIgnoreCase));ResultText.Text=matches.Count+" of "+Entries.Count+" files · "+(kind??"All files")+"\n"+models+" XOM files in this library"+(matches.Count==0&&Entries.Count>0?"\nNo matches. Try Clear filters.":"");}}
    public int CheckSearch(string query,string category){TypeBox.SelectedItem=category;Search.Text=query;Filter();return Library.Items.Count;}
    public void SearchPreview(){TypeBox.SelectedItem="Models";Search.Text="*.xom";Filter();}
    void SaveSelected(){var entry=Library.SelectedItem as Entry;if(entry==null){Status.Text="Select a file in the library first.";return;}var dialog=new SaveFileDialog{FileName=Path.GetFileName(entry.Path),Filter="All files (*.*)|*.*"};if(dialog.ShowDialog()==true)try{if(!Path.GetFullPath(dialog.FileName).Equals(Path.GetFullPath(entry.Path),StringComparison.OrdinalIgnoreCase))File.Copy(entry.Path,dialog.FileName,true);Status.Text="Saved original file: "+dialog.FileName;}catch(Exception e){Status.Text="Could not save file: "+e.Message;}}
    async Task ExportAssets(){if(Exporting){Status.Text="An export is already running.";return;}if(Entries.Count==0){Status.Text="Open an ITK or game folder first.";return;}
        var dialog=new Window{Title="Export assets",Owner=this,Width=490,Height=365,ResizeMode=ResizeMode.NoResize,WindowStartupLocation=WindowStartupLocation.CenterOwner,Background=PanelBrush,Foreground=Fore};var panel=new StackPanel{Margin=new Thickness(20)};dialog.Content=panel;
        var scope=Combo(panel,"Files to export");scope.Items.Add("Selected file");scope.Items.Add("Filtered results");scope.Items.Add("All library files");scope.SelectedIndex=Library.SelectedItem!=null?0:1;
        var format=Combo(panel,"Export format");format.Items.Add("Original files (music, video, textures, any type)");format.Items.Add("Texture images: XTX to PNG");format.Items.Add("Sound banks: XSP to PCM WAV / copy existing WAV");format.SelectedIndex=0;
        panel.Children.Add(new TextBlock{Text="XSS music stays in its original format. BIK videos are copied without transcoding. Each export uses a new folder and includes a report.",TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,18,0,4)});
        panel.Children.Add(Button("Choose destination…",delegate{dialog.DialogResult=true;}));if(dialog.ShowDialog()!=true)return;
        var selected=Library.SelectedItem as Entry;var files=scope.SelectedIndex==0?(selected==null?new List<Entry>():new List<Entry>{selected}):scope.SelectedIndex==1?Library.Items.Cast<Entry>().ToList():Entries.ToList();if(files.Count==0){Status.Text="No files selected for export.";return;}
        string destination;using(var folder=new Forms.FolderBrowserDialog()){folder.Description="Choose where to create the exported-assets folder";if(folder.ShowDialog()!=Forms.DialogResult.OK)return;destination=Path.Combine(folder.SelectedPath,"DC3_export_"+DateTime.Now.ToString("yyyyMMdd_HHmmss")+"_"+Guid.NewGuid().ToString("N").Substring(0,6));}
        string mode=new[]{"raw","png","wav"}[format.SelectedIndex];string sourceRoot=LibraryRoot;Exporting=true;Status.Text="Exporting "+files.Count+" files…";try{string summary=await Task.Run(()=>RunAssetExport(sourceRoot,files.Select(e=>e.Path).ToArray(),destination,mode));Status.Text=summary+"\n"+destination;}catch(Exception e){Status.Text="Export failed: "+e.Message;}finally{Exporting=false;}}
    public static string RunAssetExport(string sourceRoot,string[] files,string destination,string mode){string root=AppDomain.CurrentDomain.BaseDirectory;string job=Path.Combine(Path.GetTempPath(),"dc3-export-"+Guid.NewGuid().ToString("N")+".json");try{var serializer=new System.Web.Script.Serialization.JavaScriptSerializer{MaxJsonLength=int.MaxValue};File.WriteAllText(job,serializer.Serialize(new{root=sourceRoot,files=files,output=destination,mode=mode}));using(var process=new Process()){process.StartInfo=new ProcessStartInfo(Path.Combine(root,"runtime","python.exe"),Quote(Path.Combine(root,"dc3_media.py"))+" "+Quote(job)){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true,RedirectStandardOutput=true,WorkingDirectory=root};process.Start();var error=process.StandardError.ReadToEndAsync();var output=process.StandardOutput.ReadToEndAsync();process.WaitForExit();if(process.ExitCode!=0)throw new IOException(error.Result);return output.Result.Trim();}}finally{if(File.Exists(job))File.Delete(job);}}
    public async Task SelectAsset(string path){string kind=Category(path);if(kind=="Models"){await Open(path);return;}if(kind=="Animations"||kind=="Textures"){string model=Directory.GetFiles(Path.GetDirectoryName(path)).FirstOrDefault(x=>Path.GetExtension(x).Equals(".xom",StringComparison.OrdinalIgnoreCase)&&Path.GetFileNameWithoutExtension(x).Equals(Path.GetFileNameWithoutExtension(path),StringComparison.OrdinalIgnoreCase));if(model!=null){await Open(model);Status.Text="Opened matching model for "+Path.GetFileName(path)+". Choose a clip to play.";return;}}ShowFile(path);}
    void ShowFile(string path){++LoadGeneration;Playing=false;Play.Content="Play";Play.IsEnabled=false;ClipIndex=-1;GlbPath=null;if(Current!=null)Stage.Children.Remove(Current.Visual);Current=null;Lines.Children.Clear();MeshList.Children.Clear();Loading=true;ClipBox.Items.Clear();ClipBox.Items.Add("Rest pose");ClipBox.SelectedIndex=0;TextureBox.Items.Clear();TextureBox.Items.Add("Per-mesh materials");TextureBox.SelectedIndex=0;Loading=false;SyncPlaybackControls();byte[] head=new byte[64];int length;using(var f=File.OpenRead(path))length=f.Read(head,0,head.Length);TitleText.Text=Path.GetFileName(path);Stats.Text=Category(path)+" · "+new FileInfo(path).Length.ToString("N0")+" bytes\n\nHeader (hex):\n"+BitConverter.ToString(head,0,length).Replace("-"," ");Status.Text=Category(path)=="Archives"?"Nested archive contents are listed under its .contents folder. Use Save selected file to extract the archive.":"Use Export assets for original files, XTX to PNG, or XSP to WAV. Video exports retain their original format. XSS music exports as the original file.";}
    public async Task Open(string path){if(Directory.Exists(path)){await Scan(path);return;}if(Category(path)=="Archives"){int generation=++LibraryGeneration;++LoadGeneration;Playing=false;Play.Content="Play";Status.Text="Unpacking archive and nested containers… This can take a minute.";try{string folder=await Task.Run(()=>PrepareArchive(path));if(generation!=LibraryGeneration)return;var entries=await Task.Run(()=>BrowseFiles(folder));if(generation!=LibraryGeneration)return;LibraryRoot=folder;Entries=entries;Filter();Status.Text=Path.GetFileName(path)+" · "+Entries.Count+" files. Select a model, animation or texture to open its matching model.";}catch(Exception e){if(generation==LibraryGeneration)Status.Text="Could not open archive: "+e.Message;}return;}
        if(Category(path)!="Models"){LibraryRoot=Path.GetDirectoryName(path);Entries=new List<Entry>{new Entry{Path=path,Display=Path.GetFileName(path)}};Filter();ShowFile(path);return;}
        int modelGeneration=++LoadGeneration;Playing=false;Play.Content="Play";Status.Text="Preparing model and matching animations…";try{string glb=await Task.Run(()=>ConvertSource(path));if(modelGeneration!=LoadGeneration)return;LoadGlb(glb,Path.GetFileNameWithoutExtension(path));}catch(Exception e){if(modelGeneration==LoadGeneration)Status.Text="Could not open model: "+e.Message;}}
    public static string PrepareArchive(string path){string root=AppDomain.CurrentDomain.BaseDirectory;using(var process=new Process()){process.StartInfo=new ProcessStartInfo(Path.Combine(root,"runtime","python.exe"),Quote(Path.Combine(root,"dc3_archive.py"))+" "+Quote(path)){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true,RedirectStandardOutput=true,WorkingDirectory=root};process.Start();var error=process.StandardError.ReadToEndAsync();var output=process.StandardOutput.ReadToEndAsync();if(!process.WaitForExit(600000)){process.Kill();throw new IOException("Archive unpacking exceeded ten minutes.");}if(process.ExitCode!=0)throw new InvalidDataException(error.Result);string folder=output.Result.Trim();if(!Directory.Exists(folder))throw new IOException("Archive cache was not created.");return folder;}}
    public static string ConvertSource(string path){
        if(Path.GetExtension(path).Equals(".glb",StringComparison.OrdinalIgnoreCase))return path;if(!Path.GetExtension(path).Equals(".xom",StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Choose an XOM, GLB or ITK file.");
        string root=AppDomain.CurrentDomain.BaseDirectory,python=Path.Combine(root,"runtime","python.exe"),converter=Path.Combine(root,"dc3_convert.py");if(!File.Exists(python))throw new FileNotFoundException("The bundled runtime is missing. Extract the entire ZIP before starting.");
        var companions=Directory.GetFiles(Path.GetDirectoryName(path)).Where(p=>Path.GetFileNameWithoutExtension(p).Equals(Path.GetFileNameWithoutExtension(path),StringComparison.OrdinalIgnoreCase)).ToDictionary(p=>Path.GetExtension(p).ToLowerInvariant(),p=>p);
        string stamp="desktop-v07-source-animation-key-times"+String.Join("|",companions.Values.OrderBy(x=>x).Select(x=>Path.GetFullPath(x)+new FileInfo(x).Length+File.GetLastWriteTimeUtc(x).Ticks));string key;using(var sha=System.Security.Cryptography.SHA256.Create())key=BitConverter.ToString(sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(stamp))).Replace("-","");
        string cache=ModelCache(key);string output=Path.Combine(cache,"model.glb");if(File.Exists(output))return output;
        string temp=Path.Combine(cache,Guid.NewGuid().ToString("N")+".glb");string args=Quote(converter)+" "+Quote(path)+" -o "+Quote(temp)+" --clips all";if(companions.ContainsKey(".xoa"))args+=" --animation "+Quote(companions[".xoa"]);if(companions.ContainsKey(".xtx"))args+=" --xtx "+Quote(companions[".xtx"]);
        try{using(var process=new Process()){process.StartInfo=new ProcessStartInfo(python,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardError=true,RedirectStandardOutput=true,WorkingDirectory=root};process.Start();var stderr=process.StandardError.ReadToEndAsync();var stdoutTask=process.StandardOutput.ReadToEndAsync();if(!process.WaitForExit(300000)){process.Kill();throw new IOException("Conversion exceeded five minutes.");}string error=stderr.Result;string stdout=stdoutTask.Result;if(process.ExitCode!=0)throw new InvalidDataException(String.IsNullOrWhiteSpace(error)?stdout:error);}if(!File.Exists(output))File.Move(temp,output);return output;}finally{if(File.Exists(temp))File.Delete(temp);string report=Path.ChangeExtension(temp,".report.json");if(File.Exists(report))File.Delete(report);}
    }
    static string ModelCache(string key){string preferred=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"DC3ModelViewer","Cache","models-v2",key);try{CheckCache(preferred);return preferred;}catch(UnauthorizedAccessException){}catch(IOException){}
        string fallback=Path.Combine(Path.GetTempPath(),"DC3Viewer-models-"+Guid.NewGuid().ToString("N"));CheckCache(fallback);return fallback;}
    static void CheckCache(string directory){Directory.CreateDirectory(directory);string output=Path.Combine(directory,"model.glb");if(File.Exists(output))using(var stream=File.OpenRead(output)){stream.ReadByte();}string probe=Path.Combine(directory,"write-test-"+Guid.NewGuid().ToString("N"));using(var stream=new FileStream(probe,FileMode.CreateNew,FileAccess.Write,FileShare.None,1,FileOptions.DeleteOnClose)){stream.WriteByte(0);}}
    static string Quote(string path){if(path.Contains("\""))throw new InvalidDataException("Invalid path.");return "\""+path+"\"";}
    public void LoadGlb(string path,string name){
        var model=Model.Load(path);Loading=true;try{if(Current!=null)Stage.Children.Remove(Current.Visual);Current=model;GlbPath=path;Stage.Children.Insert(1,model.Visual);ClipIndex=-1;Time=0;Playing=false;Play.Content="Play";Play.IsEnabled=false;TitleText.Text=name;Stats.Text=String.Format("{0} meshes · {1:N0} vertices · {2:N0} triangles\n{3} bones · {4} animation clips · {5} textures",model.Parts.Count,model.VertexCount,model.TriangleCount,model.Nodes.Count(n=>n.Bone),model.Clips.Count,model.Textures.Count);ClipBox.Items.Clear();ClipBox.Items.Add("Rest pose");foreach(var clip in model.Clips)ClipBox.Items.Add(clip);ClipBox.SelectedIndex=0;TextureBox.Items.Clear();TextureBox.Items.Add("Per-mesh materials");for(int i=0;i<model.Textures.Count;i++)TextureBox.Items.Add(i+" · "+model.TextureNames[i]);TextureBox.SelectedIndex=0;MeshList.Children.Clear();foreach(var p in model.Parts){var part=p;var check=new CheckBox{Content=part.Name,IsChecked=true,Foreground=Fore,Margin=new Thickness(0,9,0,0)};check.Checked+=delegate{part.Visible=true;Pose();};check.Unchecked+=delegate{part.Visible=false;Pose();};MeshList.Children.Add(check);var picker=new ComboBox{Foreground=Fore,Margin=new Thickness(0,4,0,8),MaxDropDownHeight=220};picker.Items.Add("Imported material");for(int ti=0;ti<model.Textures.Count;ti++)picker.Items.Add(ti+" · "+model.TextureNames[ti]);picker.SelectedIndex=0;picker.SelectionChanged+=delegate{var chosen=picker.SelectedIndex>0?Model.Textured(model.Textures[picker.SelectedIndex-1]):part.OriginalMaterial;part.Visual.Material=chosen;part.Visual.BackMaterial=chosen;};MeshList.Children.Add(picker);}}finally{Loading=false;}Pose();AlignFloor();Frame();Status.Text="Ready · Choose a clip and press Play.";
    }
    void Export(){if(GlbPath==null){Status.Text="Open a model first.";return;}var dialog=new SaveFileDialog{Filter="GLB model (*.glb)|*.glb",FileName=TitleText.Text+".glb"};if(dialog.ShowDialog()==true){try{if(!Path.GetFullPath(dialog.FileName).Equals(Path.GetFullPath(GlbPath),StringComparison.OrdinalIgnoreCase))File.Copy(GlbPath,dialog.FileName,true);Status.Text="Saved GLB with all clips. Display overrides are not baked into exports.";}catch(Exception e){Status.Text="Could not save: "+e.Message;}}}
    void SyncPlaybackControls(){bool active=Current!=null&&ClipIndex>=0;if(!active){Playing=false;Time=0;Play.Content="Play";Updating=true;Timeline.Value=0;Updating=false;TimeText.Text="0.00 / 0.00 s";}Play.IsEnabled=active;BackFrame.IsEnabled=active;NextFrame.IsEnabled=active;Timeline.IsEnabled=active;if(SpeedBox!=null)SpeedBox.IsEnabled=active;if(Loop!=null)Loop.IsEnabled=active;}
    public void ValidateRestStatic(){SetClip(-1,0);var baseline=Current.Parts.SelectMany(p=>p.Current).ToArray();foreach(var part in Current.Parts)for(int i=0;i<part.Positions.Length;i++){var p=part.Positions[i];var expected=Current.Nodes[part.Owner].World.Transform(new Point3D(p[0],p[1],p[2]));if((part.Current[i]-expected).Length>1e-10)throw new Exception("Rest mesh differs from unposed source vertices.");}Point3D[] before=null;if(Current.Clips.Count>0){SetClip(0,Current.Clips[0].Duration*.5);before=Current.Parts.SelectMany(p=>p.Current).ToArray();Playing=true;}SetClip(-1,123);for(int i=0;i<10;i++){TogglePlayback();Seek(i+1);TickPlayback(.7);Pose();}var actual=Current.Parts.SelectMany(p=>p.Current).ToArray();if(Playing||Time!=0||Play.IsEnabled||BackFrame.IsEnabled||NextFrame.IsEnabled||Timeline.IsEnabled||SpeedBox.IsEnabled||Loop.IsEnabled||!baseline.SequenceEqual(actual))throw new Exception("Rest pose is not static.");if(Current.Clips.Count>0){SetClip(0,0);if(!Play.IsEnabled||!Timeline.IsEnabled)throw new Exception("Clip controls did not reactivate.");SetClip(0,Current.Clips[0].Duration*.5);if(!before.SequenceEqual(Current.Parts.SelectMany(p=>p.Current)))throw new Exception("Animation changed after returning from rest.");}SetClip(-1,0);}
    void TickPlayback(double dt){if(Current==null||ClipIndex<0){SyncPlaybackControls();return;}if(!Playing)return;double duration=Current.Clips[ClipIndex].Duration;double nextTime=Time+dt*new[]{.25,.5,1,2}[SpeedBox.SelectedIndex];if(duration>0&&Loop.IsChecked==true)Time=nextTime%duration;else{Time=Math.Min(nextTime,duration);if(Time>=duration){Playing=false;Play.Content="Play";}}Pose();}
    public void ValidatePlayback(){if(Current==null||Current.Clips.Count==0||Current.Clips[0].Duration<=0)return;SetClip(0,0);double duration=Duration();Loop.IsChecked=false;Playing=true;TickPlayback(duration+1);if(Playing||Time!=duration)throw new Exception("One-shot playback did not stop.");TogglePlayback();if(!Playing||Time!=0)throw new Exception("Playback did not restart.");Loop.IsChecked=true;TickPlayback(duration*1.25);if(!Playing||Math.Abs(Time-duration*.25)>1e-6)throw new Exception("Loop playback failed.");Loop.IsChecked=false;Playing=false;}
    void TogglePlayback(){if(Current==null||ClipIndex<0){SyncPlaybackControls();return;}if(!Playing&&Time>=Duration())Time=0;Playing=!Playing;Play.Content=Playing?"Pause":"Play";Watch.Restart();}
    void Seek(double t){Playing=false;Play.Content="Play";Time=Math.Max(0,Math.Min(Duration(),t));Pose();}
    double Duration(){return Current!=null&&ClipIndex>=0?Current.Clips[ClipIndex].Duration:0;}
    public void SetClip(int index,double time){if(Current==null||index < -1||index>=Current.Clips.Count)throw new ArgumentOutOfRangeException("index");ClipBox.SelectedIndex=index+1;Time=index<0?0:Math.Max(0,Math.Min(Duration(),time));Pose();}
    void Pose(){if(Loading)return;SyncPlaybackControls();if(Current==null)return;Current.Pose(ClipIndex,Time);foreach(var p in Current.Parts){p.Visual.Geometry=p.Visible&&Wire.IsChecked!=true?p.Geometry:null;}Overlays();Updating=true;Timeline.Maximum=Math.Max(Duration(),.001);Timeline.Value=Time;Updating=false;TimeText.Text=Time.ToString("0.00")+" / "+Duration().ToString("0.00")+" s";}
    public void Frame(){if(Current==null)return;var b=Current.Bounds();if(b.IsEmpty)return;Center=new Point3D(b.X+b.SizeX/2,b.Y+b.SizeY/2,b.Z+b.SizeZ/2);Radius=Math.Max(.01,Math.Sqrt(b.SizeX*b.SizeX+b.SizeY*b.SizeY+b.SizeZ*b.SizeZ)/2);double aspect=View.ActualHeight>0?View.ActualWidth/View.ActualHeight:1;Distance=Radius/Math.Sin(20*Math.PI/180)*1.2/Math.Min(1,aspect);Yaw=.8;Pitch=.28;CameraUpdate();DrawGrid();}
    void CameraUpdate(){Camera.Position=Center+new Vector3D(Math.Sin(Yaw)*Math.Cos(Pitch),Math.Sin(Pitch),Math.Cos(Yaw)*Math.Cos(Pitch))*Distance;Camera.LookDirection=Center-Camera.Position;Camera.NearPlaneDistance=Math.Max(.00001,Distance/10000);Camera.FarPlaneDistance=Math.Max(100,Distance*100);Overlays();}
    void Line(MeshGeometry3D mesh,Point3D a,Point3D b,double width){var cross=Vector3D.CrossProduct(b-a,Camera.Position-a);if(cross.LengthSquared<1e-20)return;cross.Normalize();cross*=width;int i=mesh.Positions.Count;mesh.Positions.Add(a+cross);mesh.Positions.Add(a-cross);mesh.Positions.Add(b+cross);mesh.Positions.Add(b-cross);foreach(int j in new[]{0,1,2,2,1,3})mesh.TriangleIndices.Add(i+j);}
    GeometryModel3D LineVisual(MeshGeometry3D geometry,Color color){var mat=new EmissiveMaterial(new SolidColorBrush(color));return new GeometryModel3D(geometry,mat){BackMaterial=mat};}
    void Overlays(){Lines.Children.Clear();if(Current==null)return;if(Bones.IsChecked==true){var geometry=new MeshGeometry3D();if(ClipIndex<0){foreach(var part in Current.Parts){if(!part.Visible||part.Joints==null)continue;var bind=new Dictionary<int,Point3D>();for(int j=0;j<part.Joints.Length;j++){var matrix=part.Inverse[j];if(!matrix.HasInverse)continue;matrix.Invert();matrix.Append(Current.Nodes[part.Owner].World);bind[part.Joints[j]]=matrix.Transform(new Point3D());}foreach(var item in bind){int parent=Current.Nodes[item.Key].Parent;while(parent>=0&&!bind.ContainsKey(parent))parent=Current.Nodes[parent].Parent;if(parent>=0)Line(geometry,item.Value,bind[parent],Radius*.003);}}}else{for(int i=0;i<Current.Nodes.Length;i++){var node=Current.Nodes[i];if(!node.Bone||node.Parent<0||!Current.Nodes[node.Parent].Bone)continue;Line(geometry,node.World.Transform(new Point3D()),Current.Nodes[node.Parent].World.Transform(new Point3D()),Radius*.003);}}Lines.Children.Add(LineVisual(geometry,Color.FromRgb(255,159,75)));}if(Wire.IsChecked==true){var geometry=new MeshGeometry3D();foreach(var p in Current.Parts){if(!p.Visible)continue;var edges=new HashSet<long>();for(int i=0;i<p.Indices.Length;i+=3)for(int j=0;j<3;j++){int a=p.Indices[i+j],b=p.Indices[i+(j+1)%3];long key=((long)Math.Min(a,b)<<32)|(uint)Math.Max(a,b);if(edges.Add(key))Line(geometry,p.Current[a],p.Current[b],Radius*.00065);}}Lines.Children.Add(LineVisual(geometry,Color.FromRgb(176,218,235)));}}
    void AlignFloor(){if(Current==null){FloorHeight=0;}else{var bounds=Current.Bounds();FloorHeight=bounds.IsEmpty?0:bounds.Y-.003;}DrawGrid();}
    public void ValidateFloor(){if(Current==null)return;SetClip(-1,0);for(int clip=0;clip<Current.Clips.Count;clip++){SetClip(clip,0);double floor=FloorHeight;if(Math.Abs(Current.Bounds().Y-floor-.003)>1e-8)throw new Exception("Floor does not align with clip start.");SetClip(clip,Current.Clips[clip].Duration*.5);Frame();Grid.IsChecked=false;Grid.IsChecked=true;if(FloorHeight!=floor)throw new Exception("Floor moved during a clip.");}SetClip(-1,0);if(Math.Abs(Current.Bounds().Y-FloorHeight-.003)>1e-8)throw new Exception("Rest floor did not reset.");}
    void DrawGrid(){Floor.Children.Clear();if(Grid==null||Grid.IsChecked!=true)return;double floor=FloorHeight;double size=Radius*2;var geometry=new MeshGeometry3D();for(int i=-10;i<=10;i++){double k=i*size/10;Line(geometry,new Point3D(Center.X-size,floor,Center.Z+k),new Point3D(Center.X+size,floor,Center.Z+k),Radius*.0008);Line(geometry,new Point3D(Center.X+k,floor,Center.Z-size),new Point3D(Center.X+k,floor,Center.Z+size),Radius*.0008);}Floor.Children.Add(LineVisual(geometry,Color.FromRgb(30,59,61)));}
    public void PreviewTexture(int index){TextureBox.SelectedIndex=index+1;}
    public void SavePreview(string path){UpdateLayout();var image=new RenderTargetBitmap((int)ActualWidth,(int)ActualHeight,96,96,PixelFormats.Pbgra32);image.Render((Visual)Content);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));using(var file=File.Create(path))encoder.Save(file);}
}
public static class Program {
    [STAThread] public static int Main(string[] args){
        try{var app=new Application();var viewer=new Viewer();
            if(args.Length>=3&&args[0]=="--rest-preview"){viewer.ShowInTaskbar=false;viewer.Left=-20000;viewer.Top=-20000;viewer.LoadGlb(Viewer.ConvertSource(Path.GetFullPath(args[1])),Path.GetFileNameWithoutExtension(args[1]));viewer.Show();viewer.UpdateLayout();viewer.ValidateRestStatic();viewer.Frame();viewer.SavePreview(args[2]);viewer.Close();return 0;}
            if(args.Length>=3&&args[0]=="--floor-selftest"){var lines=new List<string>();foreach(string file in Directory.GetFiles(args[1],"*.glb",SearchOption.AllDirectories)){viewer.LoadGlb(file,Path.GetFileNameWithoutExtension(file));viewer.ValidateFloor();lines.Add(Path.GetFileName(file)+": "+viewer.Current.Clips.Count+" clips; floor aligned at clip start and fixed while seeking/reframing");}File.WriteAllLines(args[2],lines);return 0;}
            if(args.Length>=3&&args[0]=="--rest-selftest"){var lines=new List<string>();foreach(string file in Directory.GetFiles(args[1],"*.glb",SearchOption.AllDirectories)){viewer.LoadGlb(file,Path.GetFileNameWithoutExtension(file));viewer.ValidateRestStatic();lines.Add(Path.GetFileName(file)+": source rest geometry, static rest, and animation roundtrip verified");}File.WriteAllLines(args[2],lines);return 0;}
            if(args.Length>=4&&args[0]=="--media-selftest"){string source=Path.GetFullPath(args[1]);string summary=Viewer.RunAssetExport(Path.GetDirectoryName(source),new[]{source},Path.GetFullPath(args[2]),args[3]);File.WriteAllText(args[2]+".txt",summary);return 0;}
            if(args.Length>=3&&args[0]=="--search-selftest"){
                viewer.ShowInTaskbar=false;viewer.Left=-20000;viewer.Top=-20000;viewer.Show();int result=0;
                app.Dispatcher.InvokeAsync(async delegate{try{await viewer.Open(Path.GetFullPath(args[1]));var rows=new List<string>();foreach(string category in new[]{"All files","Models","Textures"})foreach(string query in new[]{"xom",".xom","*.xom"," *.XOM ","en013"})rows.Add(category+" | "+query+" | "+viewer.CheckSearch(query,category));File.WriteAllLines(args[2]+".txt",rows);viewer.SearchPreview();viewer.UpdateLayout();viewer.SavePreview(args[2]);}catch(Exception e){File.WriteAllText(args[2]+".error.txt",e.ToString());result=1;}finally{viewer.Close();}});app.Run();return result;
            }
            if(args.Length>=3&&args[0]=="--archive-selftest"){
                string folder=Viewer.PrepareArchive(Path.GetFullPath(args[1]));var entries=Viewer.BrowseFiles(folder);File.WriteAllText(args[2]+".txt","Files="+entries.Count+"\nModels="+entries.Count(e=>Path.GetExtension(e.Path).Equals(".xom",StringComparison.OrdinalIgnoreCase))+"\n");
                viewer.ShowInTaskbar=false;viewer.Left=-20000;viewer.Top=-20000;viewer.Show();
                app.Dispatcher.InvokeAsync(async delegate{await viewer.Open(Path.GetFullPath(args[1]));viewer.UpdateLayout();viewer.SavePreview(args[2]);var reference=entries.FirstOrDefault(e=>Path.GetFileName(e.Path).Equals("en013.xoa",StringComparison.OrdinalIgnoreCase));if(reference!=null){await viewer.SelectAsset(reference.Path);if(viewer.Current==null||viewer.Current.Clips.Count!=63)throw new Exception("Matching archive model/animation did not load.");viewer.UpdateLayout();viewer.Frame();viewer.SavePreview(args[2]+".model.png");File.AppendAllText(args[2]+".txt","Reference=en013\nClips="+viewer.Current.Clips.Count+"\nTextures="+viewer.Current.Textures.Count+"\n");}viewer.Close();});app.Run();return 0;
            }
            if(args.Length>=3&&args[0]=="--selftest"){
                viewer.ShowInTaskbar=false;viewer.Left=-20000;viewer.Top=-20000;viewer.LoadGlb(Viewer.ConvertSource(Path.GetFullPath(args[1])),Path.GetFileNameWithoutExtension(args[1]));viewer.Show();viewer.UpdateLayout();viewer.Frame();
                var model=viewer.Current;var original=model.Parts.SelectMany(p=>p.Current).ToArray();if(model.Clips.Count>0)viewer.SetClip(0,Math.Min(1,model.Clips[0].Duration*.5));var animated=model.Parts.SelectMany(p=>p.Current).ToArray();double delta=original.Zip(animated,(a,b)=>(a-b).Length).Max();if(animated.Any(p=>double.IsNaN(p.X)||double.IsInfinity(p.X)||double.IsNaN(p.Y)||double.IsInfinity(p.Y)||double.IsNaN(p.Z)||double.IsInfinity(p.Z)))throw new Exception("Invalid animated positions.");
                var serializer=new System.Web.Script.Serialization.JavaScriptSerializer();serializer.MaxJsonLength=int.MaxValue;
                File.WriteAllText(args[2]+".vertices.json",serializer.Serialize(animated.Select(p=>new[]{p.X,p.Y,p.Z}).ToArray()));
                int poses=0;
                for(int clip=0;clip<model.Clips.Count;clip++)foreach(double t in new[]{0.0,model.Clips[clip].Duration*.5,model.Clips[clip].Duration}){model.Pose(clip,t);foreach(var part in model.Parts)foreach(var point in part.Current)if(double.IsNaN(point.X)||double.IsInfinity(point.X)||double.IsNaN(point.Y)||double.IsInfinity(point.Y)||double.IsNaN(point.Z)||double.IsInfinity(point.Z))throw new Exception("Invalid position in clip "+clip);poses++;}
                viewer.ValidatePlayback();if(model.Clips.Count>0)viewer.SetClip(0,Math.Min(1,model.Clips[0].Duration*.5));
                viewer.Dispatcher.Invoke(DispatcherPriority.Render,new Action(delegate{}));viewer.SavePreview(args[2]);File.WriteAllText(args[2]+".txt",String.Format("Meshes={0}\nVertices={1}\nTriangles={2}\nBones={3}\nClips={4}\nClipPosesChecked={5}\nMaxPoseDisplacement={6}\n",model.Parts.Count,model.VertexCount,model.TriangleCount,model.Nodes.Count(n=>n.Bone),model.Clips.Count,poses,delta));viewer.Close();return 0;
            }
            viewer.Loaded+=async delegate{if(args.Length>0)await viewer.Open(Path.GetFullPath(args[0]));else{string models=Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"..","pack_01_unpacked"));if(Directory.Exists(models))await viewer.Scan(models);}};app.Run(viewer);return 0;
        }catch(Exception error){if(args.Length>0&&(args[0]=="--selftest"||args[0]=="--floor-selftest"||args[0]=="--rest-selftest"||args[0]=="--archive-selftest")){File.WriteAllText(args[2]+".error.txt",error.ToString());return 1;}MessageBox.Show(error.Message,"Dino Crisis 3 Model Viewer",MessageBoxButton.OK,MessageBoxImage.Error);return 1;}
    }
}
}






